version: '3.8'
services:
  
  chat:
    build: .
    restart: unless-stopped
    # expose:  # note : this does not open port on host machine, it just exposes the port in docker compose's network. Use "ports" if you need to map host's port to container.
    #   - 8080
    ports:
      - 8080:8080
