version: '3.8'
services:
  
  chat:
    build: .
    restart: unless-stopped
    expose:
      - 8080
  chat-nginx:
    build: ./nginx
    restart: unless-stopped
    expose:
      - 80
    depends_on:
      - chat

networks:
  default:
    name: traefik
    external: true