version: '3.8'
services:
  
  chat:
    image: sanskarsharma/chat:v0.3.0
    restart: unless-stopped
    ports:
      - "8080:8080"
  chat-nginx:
    image: sanskarsharma/chat-nginx:v0.5.0
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - chat

